blank_issues_enabled: false
contact_links:
  - name: Kênh Hỗ Trợ Khẩn Cấp (Facebook)
    url: https://www.facebook.com/hphuoc.2007
    about: "Dành cho các vấn đề KHẨN CẤP hoặc cần hỗ trợ trực tiếp. Vui lòng không dùng cho báo cáo lỗi thông thường."
